[package]
name = "chiaki-ui"
version.workspace = true
edition.workspace = true
license.workspace = true

[dependencies]
chiaki-core.workspace = true
chiaki-settings.workspace = true
chiaki-media.workspace = true
chiaki-render.workspace = true
chiaki-input.workspace = true
thiserror.workspace = true
tracing.workspace = true
tracing-subscriber.workspace = true
