// SPDX-License-Identifier: LicenseRef-AGPL-3.0-only-OpenSSL
//
// Port of chiaki-ng lib/src/gkcrypt.c + lib/include/chiaki/gkcrypt.h.
//
// The GKCrypt is a CTR-like keystream cipher: the keystream for a key_pos is
// AES-128-ECB over (iv + key_pos/0x10) counter blocks (little-endian carry
// addition, see counter_add). Keystream blocks of 0x1000 bytes are
// pre-generated by a background thread into a circular buffer.
// GMACs are AES-128-GCM tags (4 bytes) over header/payload with a 16-byte IV
// and per-index GMAC keys (refresh every GMAC_KEY_REFRESH_KEY_POS bytes).

use crate::error::{ChiakiError, ChiakiResult};
use crate::ecdh::ECDH_SECRET_SIZE;
use aes::cipher::{BlockEncrypt, KeyInit};
use aes::Aes128;
use hmac::{Hmac, Mac};
use sha2::{Digest, Sha256};
use std::sync::{Arc, Condvar, Mutex, MutexGuard, PoisonError};
use std::thread::JoinHandle;

/// CHIAKI_GKCRYPT_BLOCK_SIZE
pub const GKCRYPT_BLOCK_SIZE: usize = 0x10;
/// CHIAKI_GKCRYPT_KEY_BUF_BLOCKS_DEFAULT (256KB)
pub const GKCRYPT_KEY_BUF_BLOCKS_DEFAULT: usize = 0x40;
/// CHIAKI_GKCRYPT_GMAC_SIZE
pub const GMAC_SIZE: usize = 4;
/// CHIAKI_GKCRYPT_GMAC_KEY_REFRESH_KEY_POS
pub const GMAC_KEY_REFRESH_KEY_POS: u64 = 45000;
/// CHIAKI_GKCRYPT_GMAC_KEY_REFRESH_IV_OFFSET
pub const GMAC_KEY_REFRESH_IV_OFFSET: u64 = 44910;
/// CHIAKI_HANDSHAKE_KEY_SIZE (session.h)
pub const HANDSHAKE_KEY_SIZE: usize = 0x10;

const KEY_BUF_CHUNK_SIZE: usize = 0x1000;

type HmacSha256 = Hmac<Sha256>;

/// chiaki_key_state_t: tracks the 64-bit key pos (32-bit wrap-around counter
/// plus carry in the high word) for key stream requests.
#[derive(Debug, Clone, Copy, Default)]
pub struct KeyState {
    prev: u64,
}

impl KeyState {
    /// chiaki_key_state_init
    pub fn new() -> Self {
        KeyState { prev: 0 }
    }

    /// chiaki_key_state_request_pos
    ///
    /// `commit` decides whether to remember this key_pos to update the state.
    /// Should only be true after authentication to avoid DoS.
    pub fn request_pos(&mut self, low: u32, commit: bool) -> u64 {
        let prev_low = self.prev as u32;
        let mut high = (self.prev >> 32) as u32;
        if seq_num_32_gt(low, prev_low) && low < prev_low {
            high = high.wrapping_add(1);
        } else if seq_num_32_lt(low, prev_low) && low > prev_low && high != 0 {
            high = high.wrapping_sub(1);
        }
        let res = ((high as u64) << 32) | low as u64;
        if commit {
            self.prev = res;
        }
        res
    }

    /// chiaki_key_state_commit: update the internal state after knowing that
    /// this key_pos is authentic.
    pub fn commit(&mut self, prev: u64) {
        self.prev = prev;
    }
}

// RFC 1982 serial number arithmetic (chiaki_seq_num_32_gt/lt).
fn seq_num_32_lt(a: u32, b: u32) -> bool {
    if a == b {
        return false;
    }
    let d = (b as i64).wrapping_sub(a as i64);
    (a < b && d < (1u64 << 31) as i64) || (a > b && -d > (1u64 << 31) as i64)
}

fn seq_num_32_gt(a: u32, b: u32) -> bool {
    if a == b {
        return false;
    }
    let d = (b as i64).wrapping_sub(a as i64);
    (a < b && d > (1u64 << 31) as i64) || (a > b && -d < (1u64 << 31) as i64)
}

/// Little-endian carry addition of `v` to `base` (counter_add in gkcrypt.c).
/// `out` and `base` must have the same length.
fn counter_add(out: &mut [u8], base: &[u8], mut v: u64) {
    for i in 0..out.len() {
        if v == 0 {
            out[i..].copy_from_slice(&base[i..]);
            return;
        }
        let r = base[i] as u64 + v;
        out[i] = r as u8;
        v = r >> 8;
    }
}

/// Generate key and IV from the handshake key and the ECDH secret
/// (gkcrypt_gen_key_iv): HMAC-SHA256 over `01 index 00 handshake_key 01 00`.
fn gen_key_iv(
    index: u8,
    handshake_key: &[u8; HANDSHAKE_KEY_SIZE],
    ecdh_secret: &[u8; ECDH_SECRET_SIZE],
) -> ChiakiResult<([u8; GKCRYPT_BLOCK_SIZE], [u8; GKCRYPT_BLOCK_SIZE])> {
    let mut data = [0u8; 3 + HANDSHAKE_KEY_SIZE + 2];
    data[0] = 1;
    data[1] = index;
    data[2] = 0;
    data[3..3 + HANDSHAKE_KEY_SIZE].copy_from_slice(handshake_key);
    data[3 + HANDSHAKE_KEY_SIZE] = 1;
    data[3 + HANDSHAKE_KEY_SIZE + 1] = 0;

    let mut mac = <HmacSha256 as Mac>::new_from_slice(ecdh_secret).map_err(|_| ChiakiError::Unknown)?;
    mac.update(&data);
    let out = mac.finalize().into_bytes();

    let mut key_base = [0u8; GKCRYPT_BLOCK_SIZE];
    key_base.copy_from_slice(&out[..GKCRYPT_BLOCK_SIZE]);
    let mut iv = [0u8; GKCRYPT_BLOCK_SIZE];
    iv.copy_from_slice(&out[GKCRYPT_BLOCK_SIZE..GKCRYPT_BLOCK_SIZE * 2]);
    Ok((key_base, iv))
}

/// chiaki_gkcrypt_gen_gmac_key: SHA256 over key_base || (iv + index * refresh),
/// the two halves XORed together.
pub fn gen_gmac_key(
    index: u64,
    key_base: &[u8; GKCRYPT_BLOCK_SIZE],
    iv: &[u8; GKCRYPT_BLOCK_SIZE],
) -> [u8; GKCRYPT_BLOCK_SIZE] {
    let mut data = [0u8; 0x20];
    data[..0x10].copy_from_slice(key_base);
    counter_add(
        &mut data[0x10..],
        iv,
        index.wrapping_mul(GMAC_KEY_REFRESH_IV_OFFSET),
    );
    let md = Sha256::digest(data);
    let mut key_out = [0u8; GKCRYPT_BLOCK_SIZE];
    for i in 0..GKCRYPT_BLOCK_SIZE {
        key_out[i] = md[i] ^ md[i + 0x10];
    }
    key_out
}

/// Generate a keystream chunk directly (chiaki_gkcrypt_gen_key_stream):
/// fills `buf` with AES-128-ECB encryptions of (iv + counter) blocks.
/// `key_pos` and `buf.len()` must be multiples of the block size.
fn gen_key_stream_raw(
    key_base: &[u8; GKCRYPT_BLOCK_SIZE],
    iv: &[u8; GKCRYPT_BLOCK_SIZE],
    key_pos: u64,
    buf: &mut [u8],
) -> ChiakiResult<()> {
    if key_pos % GKCRYPT_BLOCK_SIZE as u64 != 0 || buf.len() % GKCRYPT_BLOCK_SIZE != 0 {
        return Err(ChiakiError::InvalidData);
    }

    let cipher = Aes128::new_from_slice(key_base).map_err(|_| ChiakiError::Unknown)?;
    let mut counter_offset = key_pos / GKCRYPT_BLOCK_SIZE as u64;
    for chunk in buf.chunks_exact_mut(GKCRYPT_BLOCK_SIZE) {
        counter_add(chunk, iv, counter_offset);
        counter_offset = counter_offset.wrapping_add(1);
        let mut block = aes::Block::default();
        block.copy_from_slice(chunk);
        cipher.encrypt_block(&mut block);
        chunk.copy_from_slice(&block);
    }
    Ok(())
}

// ---------------------------------------------------------------------------
// AES-128-GCM tag (GMAC) over associated data only.
//
// The workspace has no aes-gcm crate, so the tag is computed directly per
// NIST SP 800-38D: with an empty plaintext, tag = E_K(J0) XOR GHASH_H(AAD),
// truncated to 4 bytes. Equivalent to the OpenSSL EVP_aes_128_gcm path in
// chiaki_gkcrypt_gmac (16-byte IV, AAD-only update, 4-byte tag).
// ---------------------------------------------------------------------------

/// Multiplication in GF(2^128) as used by GCM (bit-reflected byte order).
fn ghash_mul(x: &[u8; 16], y: &[u8; 16]) -> [u8; 16] {
    let mut z = [0u8; 16];
    let mut v = *y;
    for byte in x.iter() {
        let mut bit = *byte;
        for _ in 0..8 {
            if bit & 0x80 != 0 {
                for (zi, vi) in z.iter_mut().zip(v.iter()) {
                    *zi ^= vi;
                }
            }
            // v >>= 1 with reduction polynomial R = 0xe1 || 0^120
            let lsb = v[15] & 1;
            let mut carry = 0u8;
            for b in v.iter_mut() {
                let next_carry = *b & 1;
                *b = (*b >> 1) | (carry << 7);
                carry = next_carry;
            }
            if lsb == 1 {
                v[0] ^= 0xe1;
            }
            bit <<= 1;
        }
    }
    z
}

/// GHASH over whole or partial data with zero padding.
fn ghash(h: &[u8; 16], mut y: [u8; 16], data: &[u8]) -> [u8; 16] {
    for chunk in data.chunks(16) {
        for i in 0..chunk.len() {
            y[i] ^= chunk[i];
        }
        y = ghash_mul(&y, h);
    }
    y
}

/// Compute the 4-byte GMAC tag for `aad` under `key` with the 16-byte `iv`.
fn gcm_gmac_tag(
    key: &[u8; GKCRYPT_BLOCK_SIZE],
    iv: &[u8; GKCRYPT_BLOCK_SIZE],
    aad: &[u8],
) -> ChiakiResult<[u8; GMAC_SIZE]> {
    let cipher = Aes128::new_from_slice(key).map_err(|_| ChiakiError::Unknown)?;

    // H = E_K(0^128)
    let mut h_block = aes::Block::default();
    cipher.encrypt_block(&mut h_block);
    let mut h = [0u8; 16];
    h.copy_from_slice(&h_block);

    // J0 for a 16-byte (non-96-bit) IV: GHASH_H(iv || pad || [len(iv)]_64 || 0^64).
    let mut j0_data = [0u8; 32];
    j0_data[..16].copy_from_slice(iv);
    // len block: 0^64 || [len(iv) in bits]_64 (iv is exactly one block here)
    j0_data[24..32].copy_from_slice(&((iv.len() as u64) * 8).to_be_bytes());
    let j0 = ghash(&h, [0u8; 16], &j0_data);

    // S = GHASH_H(aad || pad || [len(aad)]_64 || [0]_64) (plaintext is empty).
    let mut s_data = Vec::with_capacity(aad.len() + 16);
    s_data.extend_from_slice(aad);
    let pad = (16 - (aad.len() % 16)) % 16;
    s_data.resize(aad.len() + pad, 0);
    s_data.extend_from_slice(&((aad.len() as u64) * 8).to_be_bytes());
    s_data.extend_from_slice(&0u64.to_be_bytes());
    let s = ghash(&h, [0u8; 16], &s_data);

    // tag = E_K(J0) XOR S, truncated
    let mut ej0 = aes::Block::from(j0);
    cipher.encrypt_block(&mut ej0);
    let mut tag = [0u8; GMAC_SIZE];
    for i in 0..GMAC_SIZE {
        tag[i] = ej0[i] ^ s[i];
    }
    Ok(tag)
}

// ---------------------------------------------------------------------------

struct Inner {
    /// circular buffer of the ctr mode key stream
    key_buf: Vec<u8>,
    key_buf_size: u64,
    /// size of key_buf that is already populated (on startup)
    key_buf_populated: u64,
    /// minimal key pos currently in key_buf
    key_buf_key_pos_min: u64,
    /// offset in key_buf of the minimal key pos
    key_buf_start_offset: usize,
    /// last key pos that has been requested
    last_key_pos: u64,
    key_gmac_current: [u8; GKCRYPT_BLOCK_SIZE],
    key_gmac_index_current: u64,
    key_buf_thread_stop: bool,
}

impl Inner {
    fn key_buf_should_generate(&self) -> bool {
        self.last_key_pos > self.key_buf_key_pos_min + self.key_buf_populated / 2
    }
}

struct Shared {
    inner: Mutex<Inner>,
    cond: Condvar,
}

fn lock(shared: &Shared) -> MutexGuard<'_, Inner> {
    shared
        .inner
        .lock()
        .unwrap_or_else(PoisonError::into_inner)
}

/// ChiakiGKCrypt: keystream cipher + GMAC provider. Shared as `Arc<GKCrypt>`.
pub struct GKCrypt {
    index: u8,
    iv: [u8; GKCRYPT_BLOCK_SIZE],
    key_base: [u8; GKCRYPT_BLOCK_SIZE],
    key_gmac_base: [u8; GKCRYPT_BLOCK_SIZE],
    has_key_buf: bool,
    shared: Arc<Shared>,
    key_buf_thread: Option<JoinHandle<()>>,
}

impl GKCrypt {
    /// chiaki_gkcrypt_new / chiaki_gkcrypt_init
    ///
    /// `key_buf_chunks` (times 0x1000 bytes) decides the size of the
    /// pre-generated keystream buffer; if 0, every request generates directly
    /// and no thread is spawned.
    pub fn new(
        key_buf_chunks: usize,
        index: u8,
        handshake_key: &[u8; HANDSHAKE_KEY_SIZE],
        ecdh_secret: &[u8; ECDH_SECRET_SIZE],
    ) -> ChiakiResult<Arc<Self>> {
        let key_buf_size = key_buf_chunks * KEY_BUF_CHUNK_SIZE;

        let (key_base, iv) = gen_key_iv(index, handshake_key, ecdh_secret)?;
        let key_gmac_base = gen_gmac_key(0, &key_base, &iv);

        let shared = Arc::new(Shared {
            inner: Mutex::new(Inner {
                key_buf: vec![0u8; key_buf_size],
                key_buf_size: key_buf_size as u64,
                key_buf_populated: 0,
                key_buf_key_pos_min: 0,
                key_buf_start_offset: 0,
                last_key_pos: 0,
                key_gmac_current: key_gmac_base,
                key_gmac_index_current: 0,
                key_buf_thread_stop: false,
            }),
            cond: Condvar::new(),
        });

        let key_buf_thread = if key_buf_size > 0 {
            let shared = Arc::clone(&shared);
            let key_base = key_base;
            let iv = iv;
            Some(
                std::thread::Builder::new()
                    .name("Chiaki GKCrypt".to_owned())
                    .spawn(move || key_buf_thread_func(shared, key_base, iv))
                    .map_err(|_| ChiakiError::Thread)?,
            )
        } else {
            None
        };

        Ok(Arc::new(GKCrypt {
            index,
            iv,
            key_base,
            key_gmac_base,
            has_key_buf: key_buf_size > 0,
            shared,
            key_buf_thread,
        }))
    }

    pub fn index(&self) -> u8 {
        self.index
    }

    /// The AES keystream key ("key_base"). Immutable after init.
    pub fn key_base(&self) -> &[u8; GKCRYPT_BLOCK_SIZE] {
        &self.key_base
    }

    /// The counter base IV. Immutable after init.
    pub fn iv(&self) -> &[u8; GKCRYPT_BLOCK_SIZE] {
        &self.iv
    }

    /// chiaki_gkcrypt_gen_key_stream: generate keystream for an exact key_pos,
    /// bypassing the circular buffer.
    pub fn gen_key_stream(&self, key_pos: u64, buf: &mut [u8]) -> ChiakiResult<()> {
        gen_key_stream_raw(&self.key_base, &self.iv, key_pos, buf)
    }

    /// chiaki_gkcrypt_get_key_stream: fetch keystream from the circular buffer
    /// (or generate directly if not buffered/out of range).
    pub fn get_key_stream(&self, key_pos: u64, buf: &mut [u8]) -> ChiakiResult<()> {
        if !self.has_key_buf {
            return self.gen_key_stream(key_pos, buf);
        }

        let buf_size = buf.len() as u64;
        let signal;
        let err = {
            let mut guard = lock(&self.shared);

            if key_pos + buf_size > guard.last_key_pos {
                guard.last_key_pos = key_pos + buf_size;
            }
            signal = guard.key_buf_should_generate();

            if key_pos < guard.key_buf_key_pos_min
                || key_pos + buf_size >= guard.key_buf_key_pos_min + guard.key_buf_populated
            {
                tracing::warn!(
                    "Requested key stream for key pos {:#x} on GKCrypt {}, but it's not in the buffer: \
                     key buf size {:#x}, start offset: {:#x}, populated: {:#x}, min key pos: {:#x}, last key pos: {:#x}",
                    key_pos,
                    self.index,
                    guard.key_buf_size,
                    guard.key_buf_start_offset,
                    guard.key_buf_populated,
                    guard.key_buf_key_pos_min,
                    guard.last_key_pos
                );
                drop(guard);
                self.gen_key_stream(key_pos, buf)
            } else {
                let size = guard.key_buf.len();
                let mut offset_in_buf =
                    (key_pos - guard.key_buf_key_pos_min) as usize + guard.key_buf_start_offset;
                offset_in_buf %= size;
                let end = offset_in_buf + buf.len();
                if end > size {
                    let excess = end - size;
                    let (left, right) = buf.split_at_mut(buf.len() - excess);
                    left.copy_from_slice(&guard.key_buf[offset_in_buf..offset_in_buf + left.len()]);
                    right.copy_from_slice(&guard.key_buf[..excess]);
                } else {
                    buf.copy_from_slice(&guard.key_buf[offset_in_buf..end]);
                }
                Ok(())
            }
        };

        if signal {
            self.shared.cond.notify_all();
        }
        err
    }

    /// chiaki_gkcrypt_decrypt / chiaki_gkcrypt_encrypt (XOR with keystream).
    pub fn decrypt(&self, key_pos: u64, buf: &mut [u8]) -> ChiakiResult<()> {
        let padding_pre = (key_pos % GKCRYPT_BLOCK_SIZE as u64) as usize;
        let full_size = ((padding_pre + buf.len() + GKCRYPT_BLOCK_SIZE - 1)
            / GKCRYPT_BLOCK_SIZE)
            * GKCRYPT_BLOCK_SIZE;

        let mut key_stream = vec![0u8; full_size];
        self.get_key_stream(key_pos - padding_pre as u64, &mut key_stream)?;

        for (b, k) in buf.iter_mut().zip(key_stream[padding_pre..].iter()) {
            *b ^= k;
        }
        Ok(())
    }

    /// chiaki_gkcrypt_encrypt (identical to decrypt, XOR with keystream).
    pub fn encrypt(&self, key_pos: u64, buf: &mut [u8]) -> ChiakiResult<()> {
        self.decrypt(key_pos, buf)
    }

    /// chiaki_gkcrypt_gmac: 4-byte AES-128-GCM tag over `buf` with the
    /// 16-byte counter IV for `key_pos` and the GMAC key for its index.
    pub fn gmac(&self, key_pos: u64, buf: &[u8]) -> ChiakiResult<[u8; GMAC_SIZE]> {
        let mut iv = [0u8; GKCRYPT_BLOCK_SIZE];
        counter_add(&mut iv, &self.iv, key_pos / 0x10);

        let key_index = key_pos.saturating_sub(1) / GMAC_KEY_REFRESH_KEY_POS;

        let gmac_key = {
            let mut guard = lock(&self.shared);
            if key_index > guard.key_gmac_index_current {
                let key = gen_gmac_key(key_index, &self.key_gmac_base, &self.iv);
                guard.key_gmac_current = key;
                guard.key_gmac_index_current = key_index;
                key
            } else if key_index < guard.key_gmac_index_current {
                // gen_tmp_gmac_key: index 0 means the base key itself
                if key_index == 0 {
                    self.key_gmac_base
                } else {
                    gen_gmac_key(key_index, &self.key_gmac_base, &self.iv)
                }
            } else {
                guard.key_gmac_current
            }
        };

        gcm_gmac_tag(&gmac_key, &iv, buf)
    }
}

impl Drop for GKCrypt {
    fn drop(&mut self) {
        {
            let mut guard = lock(&self.shared);
            guard.key_buf_thread_stop = true;
            self.shared.cond.notify_all();
        }
        if let Some(handle) = self.key_buf_thread.take() {
            let _ = handle.join();
        }
    }
}

fn key_buf_mutex_pred(g: &Inner) -> bool {
    if g.key_buf_thread_stop {
        return true;
    }
    if g.key_buf_populated < g.key_buf_size {
        return true;
    }
    g.key_buf_should_generate()
}

fn key_buf_thread_func(shared: Arc<Shared>, key_base: [u8; GKCRYPT_BLOCK_SIZE], iv: [u8; GKCRYPT_BLOCK_SIZE]) {
    let mut guard = lock(&shared);
    loop {
        // chiaki_cond_wait_pred: while(!pred) cond_wait
        loop {
            if key_buf_mutex_pred(&guard) {
                break;
            }
            guard = match shared.cond.wait(guard) {
                Ok(g) => g,
                Err(e) => e.into_inner(),
            };
        }

        if guard.key_buf_thread_stop {
            break;
        }

        if guard.last_key_pos > guard.key_buf_key_pos_min + guard.key_buf_populated {
            // skip ahead if the last key pos is already beyond our buffer
            let key_pos = (guard.last_key_pos / KEY_BUF_CHUNK_SIZE as u64) * KEY_BUF_CHUNK_SIZE as u64;
            tracing::warn!(
                "Already requested a higher key pos than in the buffer, skipping ahead from min {:#x} to {:#x}",
                guard.key_buf_key_pos_min,
                key_pos
            );
            guard.key_buf_key_pos_min = key_pos;
            guard.key_buf_start_offset = 0;
            guard.key_buf_populated = 0;
        } else if guard.key_buf_populated == guard.key_buf_size {
            guard.key_buf_start_offset = (guard.key_buf_start_offset + KEY_BUF_CHUNK_SIZE)
                % guard.key_buf.len();
            guard.key_buf_key_pos_min += KEY_BUF_CHUNK_SIZE as u64;
            guard.key_buf_populated -= KEY_BUF_CHUNK_SIZE as u64;
        }

        // gkcrypt_generate_next_chunk (generation happens without the lock)
        let buf_offset =
            (guard.key_buf_start_offset + guard.key_buf_populated as usize) % guard.key_buf.len();
        let key_pos = guard.key_buf_key_pos_min + guard.key_buf_populated;
        drop(guard);

        let mut chunk = vec![0u8; KEY_BUF_CHUNK_SIZE];
        let err = gen_key_stream_raw(&key_base, &iv, key_pos, &mut chunk);

        guard = lock(&shared);
        match err {
            Ok(()) => {
                guard.key_buf[buf_offset..buf_offset + chunk.len()].copy_from_slice(&chunk);
                guard.key_buf_populated += chunk.len() as u64;
            }
            Err(err) => {
                tracing::error!("GKCrypt failed to generate key stream chunk: {}", err);
                break;
            }
        }
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    fn hx(s: &str) -> Vec<u8> {
        hex::decode(s).expect("valid hex")
    }

    fn k16(s: &str) -> [u8; 16] {
        let v = hx(s);
        let mut out = [0u8; 16];
        out.copy_from_slice(&v);
        out
    }

    fn k32(s: &str) -> [u8; 32] {
        let v = hx(s);
        let mut out = [0u8; 32];
        out.copy_from_slice(&v);
        out
    }

    const HANDSHAKE_KEY_TEST: [u8; 16] = [
        0x83, 0xcf, 0x93, 0x1a, 0x6a, 0xa7, 0x69, 0xa6, 0xc4, 0x48, 0x5d, 0x19, 0xc1, 0x5c, 0xcc,
        0x52,
    ];
    const ECDH_SECRET_TEST: [u8; 32] = [
        0x73, 0xc8, 0xd5, 0x49, 0xc4, 0xd9, 0xdb, 0x50, 0x2e, 0xc0, 0x44, 0xea, 0x33, 0x64, 0x8c,
        0x6a, 0xc9, 0xf3, 0x6c, 0x41, 0xb6, 0xa0, 0x50, 0x4f, 0xe0, 0x93, 0xde, 0xfb, 0x61, 0x9b,
        0x09, 0x73,
    ];

    // Golden vectors from chiaki-ng test/gkcrypt.c.

    #[test]
    fn test_key_stream() {
        let handshake_key = HANDSHAKE_KEY_TEST;
        let ecdh_secret = ECDH_SECRET_TEST;
        let gkcrypt_key = k16("08816fa2e5558961d5a286d90eec5b8c");
        let gkcrypt_iv = k16("2ae1bb3d84dc9aa9c352a4cf3ffb8b72");
        let key_stream = hx("0f6d89855ba786745ba1fe5c81196cd554c41ccaf6e934a4892698b06212b31a");
        let key_stream_high =
            hx("14319ff8be0817a4fc28490b1e5f7b7efae914dec6dfe75dd69c753f9462d52c");

        let gkcrypt = GKCrypt::new(0, 42, &handshake_key, &ecdh_secret).unwrap();

        assert_eq!(gkcrypt.key_base(), &gkcrypt_key);
        assert_eq!(gkcrypt.iv(), &gkcrypt_iv);

        let mut key_stream_result = [0u8; 0x20];
        gkcrypt
            .gen_key_stream(0x30, &mut key_stream_result)
            .unwrap();
        assert_eq!(&key_stream_result[..], &key_stream[..]);

        let key_pos = (1u64 << 32) + 0x420;
        gkcrypt
            .gen_key_stream(key_pos, &mut key_stream_result)
            .unwrap();
        assert_eq!(&key_stream_result[..], &key_stream_high[..]);
    }

    #[test]
    fn test_endecrypt() {
        let handshake_key = k16("14f1e6946c5dcea8b7aa4850f64d21ac");
        let ecdh_secret = k32("0ceb7709834d7afc50b8468cc63c1e7c4e4a88934280c128e61ee9d41b8c6936");
        let gkcrypt_key = k16("277aa51dacd15f0e5412face0dc4636a");
        let gkcrypt_iv = k16("ef2040c2153c0266321f42bbf450344d");
        let clear_data = hx("4e619f945d4b8ebd2a154d036acd49569cc75ce3e700179a38d9695345f90cb58c05650f70");
        let enc_data = hx("23f48dd8aaf9589bb1944fad2b8daa8d2588faf8b6d417f45f78ecf54e3720b0768107679a");
        let enc_data_high = hx("2b9ee983274408b117f537a0d9c2c6059578b278fd178c52f4179dee3f62e63001614cf4a1");

        let gkcrypt = GKCrypt::new(0, 42, &handshake_key, &ecdh_secret).unwrap();

        assert_eq!(gkcrypt.key_base(), &gkcrypt_key);
        assert_eq!(gkcrypt.iv(), &gkcrypt_iv);

        let mut key_stream_result = [0u8; 0x20];
        gkcrypt
            .gen_key_stream(0x30, &mut key_stream_result)
            .unwrap();

        let mut buf = clear_data.clone();
        gkcrypt.encrypt(0x11, &mut buf).unwrap();
        assert_eq!(buf, enc_data);

        let mut buf = clear_data.clone();
        gkcrypt.decrypt(0x11, &mut buf).unwrap();
        assert_eq!(buf, enc_data);

        // High
        let key_pos_high = (1u64 << 32) + 0x420;
        let mut buf = clear_data.clone();
        gkcrypt.encrypt(key_pos_high, &mut buf).unwrap();
        assert_eq!(buf, enc_data_high);

        let mut buf = clear_data.clone();
        gkcrypt.decrypt(key_pos_high, &mut buf).unwrap();
        assert_eq!(buf, enc_data_high);
    }

    // The C test memsets the whole struct and only sets key_gmac_current/iv;
    // the equivalent here drives the same code path (gcm_gmac_tag +
    // counter_add + gen_gmac_key with a zeroed key_gmac_base) directly.
    #[test]
    fn test_gmac() {
        let gmac_key = k16("b64b1e653fbba7ab80b31e5a324decc0");
        let gmac_iv = k16("7cc8d0199edfd8c3b50f32ee36336a5a");

        let buf = hx(
            "0300180019000250210500000000000069a000f9f89824da560b74ec6815d31f8543aad3cdb8502e90a4b085f3be9a4797c1ab5fa5fd625c261a54367230c32be02c5a8607f5dc1255b48e175be47f965586f0fb45e2f8e87d5f3a8bb0646c54f68c4ea412a3267f225b1998bad4ad9f5f63af1f978c1749a33071d2b0492c75a289da50fd9b0841982d8c0b9279ae602383ef5cdace71082d0b17625648c5e20f221ddcccc282a68eec1e040c08aaa2806c4fd36fc19b769a58aa2556eff2fd77f0324e83e23025a55af1dfc875a2b62bfdacbc6309a1cc2bf546ef49838f0bc147ac5a002eec1cd00a66b5ee9eadc9642dcb980f43a6e14ce79f2dab9401d7528419",
        );

        let key_pos = 0x69a0u64;
        let key_pos_high = (1u64 << 32) + 0x420;

        let gmac_expected = [0x6f, 0x81, 0x10, 0x97];
        let gmac_expected_high = [0x4a, 0x30, 0x98, 0x10];

        // Low: key_index == 0 == key_gmac_index_current -> current key
        let mut iv = [0u8; 16];
        counter_add(&mut iv, &gmac_iv, key_pos / 0x10);
        let gmac = gcm_gmac_tag(&gmac_key, &iv, &buf).unwrap();
        assert_eq!(gmac, gmac_expected);

        // High: key_index > 0, new key generated from a zeroed key_gmac_base
        let key_index = (key_pos_high - 1) / GMAC_KEY_REFRESH_KEY_POS;
        let new_key = gen_gmac_key(key_index, &[0u8; 16], &gmac_iv);
        let mut iv = [0u8; 16];
        counter_add(&mut iv, &gmac_iv, key_pos_high / 0x10);
        let gmac = gcm_gmac_tag(&new_key, &iv, &buf).unwrap();
        assert_eq!(gmac, gmac_expected_high);
    }

    #[test]
    fn test_gen_gmac_key() {
        let key_initial = k16("beeba0f03d05707d3ac73cd732b94801");
        let iv = k16("e87187e763e0df463dc2024a2cd29c45");
        let key_result = k16("e3db92d9ddd36899aefd9b15e1a6878b");

        let key_out = gen_gmac_key(1, &key_initial, &iv);
        assert_eq!(key_out, key_result);
    }

    #[test]
    fn test_gmac_split() {
        let gmac_key = k16("35958187ebcb63549000d7d5bdf4c5f4");
        let gmac_iv = k16("b8defca448f04c3fd5940e1c046463b1");

        let buf = hx(
            "02001e00090020080103000000000000adf0024e002c6f3b6c2e4a279c503484ea37c776ab92304361c71dcbc43594cc44e2fa8986475ec201394c9f67b36e354497f428e25112daf52c431c49462c53e3e97661872b7ae32fbb9f4d668a31bc649d060d4add4221733c9721845365537af4577761ae0c7a4290fc6bbb386e52b6e5260fd22af15650dd65149ee3b570675547cd8ec1baf672b1b4111b25d43d19b5f5dd2fefd6d1afb4dc93e53cc3a464b3add3fc238486f7f910df156e0c6e439a633bb53805f94a684afb95949d31fd843143850d8ebb66ca4d3b0a75e5ebded5f88285b2ccdb709ea9e2b0ac760128ea1039b7477882c9a42416c3e51602469207db3ab0d0ddc015dc05c761e57d82d04c1744b4fa28d894c1f4d0b3506a2581987b4967a219b241e5d2df9a4fc960ffb291e85f7767ffc0a17657eb6134578075db03c553f5b3a861df0fb6e6c439a0cde9a632b8ba469c431649659d7187f337e5e0c6df5e4cc5209b16ed132d63792bd0514400448c7c2cc68220caca1f7fea71b7845b8c945b92b6efbe5f083d05b2fbcb5a01d416718d9ef58dae804090feef5da474f3e34a9a678ba6b55918614f425f2b7439a8305d8df1ad254f41ca27da07754946d781aa2761569c294090220acd3a7bb48596078013123f2527a0f626bdd1b095bd26ba49a6810731d3e125daab71b9651d13ab825295b362a64848b8d8552698a1c957661cacb1c75ffa44c6d819018d411fc70f891def349a68778c",
        );

        let key_pos = 0xadf0u64;
        let key_pos_high = (1u64 << 32) + 0x420;

        let gmac_expected = [0xd6, 0x6a, 0x07, 0xb7];
        let gmac_expected_high = [0xf0, 0x17, 0x95, 0x3c];

        // Low
        let mut iv = [0u8; 16];
        counter_add(&mut iv, &gmac_iv, key_pos / 0x10);
        let gmac = gcm_gmac_tag(&gmac_key, &iv, &buf).unwrap();
        assert_eq!(gmac, gmac_expected);

        // High
        let key_index = (key_pos_high - 1) / GMAC_KEY_REFRESH_KEY_POS;
        let new_key = gen_gmac_key(key_index, &[0u8; 16], &gmac_iv);
        let mut iv = [0u8; 16];
        counter_add(&mut iv, &gmac_iv, key_pos_high / 0x10);
        let gmac = gcm_gmac_tag(&new_key, &iv, &buf).unwrap();
        assert_eq!(gmac, gmac_expected_high);
    }

    #[test]
    fn test_gmac_multiple_of_key_refresh() {
        let handshake_key = k16("7058375091ead1377158ecb30bea2387");
        let ecdh_secret = k32(
            "3c3af0ecd6331bb16d244f4819de063dc70eac9570ac249286a724d07a375552",
        );

        let data = hx(
            "0311a411a5000250210500000000006b1de00083f1c47971e4677cccb792078bba8a08d662f5075d4a2014b3e70e5c77fd6d60a3c548a9c061f984f63762acbc1f5de44090547137ab337eaaa5f4c40903f4b6a12f022753c6a5b19c8fb469d65c7f795f1447cca88b37f7776d01f45b59ca96730a20f37ad1d27ffeb666f4db10aff307ee498aa1a573d823830e0c0c3a49dcd80cc8e4b6f23c6d256a7da01c3a8e0f3f2547118967c4f9acc7e29374c6fbdd4857ae53e2f4178062f309d8d47a466b08769c2981914e57af70b63278989e85f2e36915afd432540fd4a2fcf536dc0645f406a3382102fdf05175eab1f68e3935fd7574adbc3efbee7d0f2d76befdee",
        );

        let crypt_index = 3u8;
        // % GMAC_KEY_REFRESH_KEY_POS == 0
        let key_pos = 0x6b1de0u64;
        let gmac_expected = [0x20, 0xcc, 0xa5, 0xf1];

        let gkcrypt = GKCrypt::new(0, crypt_index, &handshake_key, &ecdh_secret).unwrap();

        let gmac = gkcrypt.gmac(key_pos, &data).unwrap();
        assert_eq!(gmac, gmac_expected);
    }

    // Buffered keystream: the background thread pre-fills the circular buffer;
    // requests inside the buffered range must match direct generation.
    #[test]
    fn test_key_stream_buffered() {
        let handshake_key = HANDSHAKE_KEY_TEST;
        let ecdh_secret = ECDH_SECRET_TEST;

        let gkcrypt = GKCrypt::new(4, 7, &handshake_key, &ecdh_secret).unwrap();

        // Wait until the buffer is fully populated (thread fills 4 chunks).
        let deadline = std::time::Instant::now() + std::time::Duration::from_secs(5);
        loop {
            let populated = lock(&gkcrypt.shared).key_buf_populated;
            if populated == 4 * KEY_BUF_CHUNK_SIZE as u64 {
                break;
            }
            assert!(
                std::time::Instant::now() < deadline,
                "key buf not populated in time"
            );
            std::thread::sleep(std::time::Duration::from_millis(2));
        }

        // In-buffer request (offset 0x30, 0x20 bytes)
        let mut buffered = [0u8; 0x20];
        gkcrypt.get_key_stream(0x30, &mut buffered).unwrap();

        let mut direct = [0u8; 0x20];
        gen_key_stream_raw(gkcrypt.key_base(), gkcrypt.iv(), 0x30, &mut direct).unwrap();
        assert_eq!(buffered, direct);

        // Request spanning the end of the circular buffer (wrap-around)
        let buf_size = 4 * KEY_BUF_CHUNK_SIZE as u64;
        let mut buffered = vec![0u8; 0x100];
        gkcrypt.get_key_stream(buf_size - 0x80, &mut buffered).unwrap();
        let mut direct = vec![0u8; 0x100];
        gen_key_stream_raw(gkcrypt.key_base(), gkcrypt.iv(), buf_size - 0x80, &mut direct).unwrap();
        assert_eq!(buffered, direct);

        // decrypt via the buffered path must match direct keystream XOR
        let clear = hx("00112233445566778899aabbccddeeff00112233445566778899aabbccddeeff");
        let mut enc = clear.clone();
        gkcrypt.encrypt(0x1234, &mut enc).unwrap();
        let mut expected = clear.clone();
        for (i, b) in expected.iter_mut().enumerate() {
            let pos = 0x1234 + i as u64;
            let mut ks = [0u8; 16];
            gen_key_stream_raw(gkcrypt.key_base(), gkcrypt.iv(), (pos / 16) * 16, &mut ks).unwrap();
            *b ^= ks[(pos % 16) as usize];
        }
        assert_eq!(enc, expected);
    }

    #[test]
    fn test_counter_add() {
        let base = k16("ffffffffffffffffffffffffffffffff");
        let mut out = [0u8; 16];
        counter_add(&mut out, &base, 2);
        // carry propagates through all bytes
        assert_eq!(out[0], 0x01);
        assert_eq!(&out[1..], &[0x00; 15][..]);

        let base = k16("2ae1bb3d84dc9aa9c352a4cf3ffb8b72");
        let mut out = [0u8; 16];
        counter_add(&mut out, &base, 0);
        assert_eq!(out, base);

        let mut out = [0u8; 16];
        counter_add(&mut out, &base, 0x123);
        assert_eq!(out[0], base[0] + 0x23);
        assert_eq!(out[1], base[1] + 0x1);
        assert_eq!(&out[2..], &base[2..]);
    }

    // Golden vectors from chiaki-ng test/keystate.c.

    #[test]
    fn test_key_state() {
        let mut state = KeyState::new();

        let pos = state.request_pos(0, true);
        assert_eq!(pos, 0);
        let pos = state.request_pos(0x1337, true);
        assert_eq!(pos, 0x1337);
        let pos = state.request_pos(0xffff0000, true);
        assert_eq!(pos, 0xffff0000);
        let pos = state.request_pos(0x1337, true);
        assert_eq!(pos, 0x100001337);
        let pos = state.request_pos(0xffff1337, true);
        assert_eq!(pos, 0xffff1337);
        let pos = state.request_pos(0x50000000, true);
        assert_eq!(pos, 0x150000000);
        let pos = state.request_pos(0xb0000000, true);
        assert_eq!(pos, 0x1b0000000);
        let pos = state.request_pos(0x00000000, true);
        assert_eq!(pos, 0x200000000);
    }

    #[test]
    fn test_key_state_nocommit() {
        let mut state = KeyState::new();

        let pos = state.request_pos(0, false);
        assert_eq!(pos, 0);
        let pos = state.request_pos(0x1337, false);
        assert_eq!(pos, 0x1337);
        let pos = state.request_pos(0xffff0000, false);
        assert_eq!(pos, 0xffff0000);
        let pos = state.request_pos(0x1337, false);
        assert_eq!(pos, 0x1337);
        let pos = state.request_pos(0xffff1337, false);
        assert_eq!(pos, 0xffff1337);
        let pos = state.request_pos(0x50000000, false);
        assert_eq!(pos, 0x50000000);
        let pos = state.request_pos(0xb0000000, false);
        assert_eq!(pos, 0xb0000000);
        let pos = state.request_pos(0x00000000, false);
        assert_eq!(pos, 0);
    }
}
